tasks:
  - name: Jupyter Notebook
    init: >
      pip install -r "requirements.txt";
    command: >
      pip install -r "requirements.txt";
      jupyter notebook --NotebookApp.allow_origin=\'$(gp url 8888)\'

ports:
  - port: 9000-9099
    onOpen: ignore
  - port: 8888
    onOpen: open-browser

# Install necessary packages
image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - ms-toolsai.jupyter
