tasks:
  - name: Jupyter Notebook
    init: >
      pip install -r "requirements.txt";
    command: >
      pip install -r "requirements.txt";

ports:
  - port: 9000-9099
    onOpen: ignore

# Install necessary packages
image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - ms-toolsai.jupyter
